# Uncomment the next line to define a global platform for your project
# platform :ios, '17.0'

target 'PokaNetFilms' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PokaNetFilms
  pod 'SnapKit'

end
